import { forwardRef } from 'react'
import type { Img } from '../content/projects'
import { deferredImagePlaceholder } from '../motion/nearViewportImages'

const previewWidths = [320, 640, 960, 1600, 1920]

function variant(src: string, width: number, format: 'avif' | 'webp') {
  return src.replace(/-\d+(-grey)?\.(?:avif|webp)$/, `-${width}$1.${format}`)
}

export function projectSrcSet(img: Img, format: 'avif' | 'webp') {
  const widths = previewWidths.filter((width) => width < img.width)
  const full = img.src.replace(/\.(?:avif|webp)$/, `.${format}`)
  return [...widths.map((width) => `${variant(img.src, width, format)} ${width}w`), `${full} ${img.width}w`].join(', ')
}

type ProjectImageProps = {
  img: Img
  sizes: string
  alt?: string
  className?: string
  loading?: 'eager' | 'lazy'
  fetchPriority?: 'high' | 'low' | 'auto'
  deferUntilNear?: boolean
}

export const ProjectImage = forwardRef<HTMLImageElement, ProjectImageProps>(function ProjectImage(
  { img, sizes, alt = img.alt, className = '', loading = 'lazy', fetchPriority, deferUntilNear = false },
  ref,
) {
  // Only width-suffixed WebP masters have the responsive AVIF/WebP family
  // generated by scripts/project-images.mjs. A JPEG (such as the About
  // portrait) must keep its real URL and must not claim fake widths/formats.
  if (!/-\d+(?:-grey)?\.(?:avif|webp)$/i.test(img.src)) {
    return (
      <img
        ref={ref}
        src={deferUntilNear ? deferredImagePlaceholder() : img.src}
        data-deferred-image={deferUntilNear ? '' : undefined}
        data-src={deferUntilNear ? img.src : undefined}
        alt={alt}
        width={img.width}
        height={img.height}
        loading={loading}
        decoding={loading === 'eager' ? 'sync' : 'async'}
        fetchPriority={fetchPriority}
        className={className}
      />
    )
  }

  const avifSrcSet = projectSrcSet(img, 'avif')
  const webpSrcSet = projectSrcSet(img, 'webp')
  return (
    <picture className="contents" data-deferred-image={deferUntilNear ? '' : undefined}>
      <source
        type="image/avif"
        srcSet={deferUntilNear ? undefined : avifSrcSet}
        data-srcset={deferUntilNear ? avifSrcSet : undefined}
        sizes={deferUntilNear ? undefined : sizes}
        data-sizes={deferUntilNear ? sizes : undefined}
      />
      <img
        ref={ref}
        src={deferUntilNear ? deferredImagePlaceholder() : img.src}
        srcSet={deferUntilNear ? undefined : webpSrcSet}
        sizes={deferUntilNear ? undefined : sizes}
        data-src={deferUntilNear ? img.src : undefined}
        data-srcset={deferUntilNear ? webpSrcSet : undefined}
        data-sizes={deferUntilNear ? sizes : undefined}
        alt={alt}
        width={img.width}
        height={img.height}
        loading={loading}
        decoding={loading === 'eager' ? 'sync' : 'async'}
        fetchPriority={fetchPriority}
        className={className}
      />
    </picture>
  )
})
